# Use OpenJDK 17
FROM openjdk:17-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy built jar into container
COPY target/user-services-1.0-SNAPSHOT.jar user-services-1.0-SNAPSHOT.jar

# Expose port for container
EXPOSE 8081

# Run the jar file
ENTRYPOINT ["java", "-jar", "user-services-1.0-SNAPSHOT.jar"]
