# Use OpenJDK 17
FROM openjdk:17-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy built jar into container
COPY target/order-services-1.0-SNAPSHOT.jar order-services-1.0-SNAPSHOT.jar

# Expose port for container
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "order-services-1.0-SNAPSHOT.jar"]
